### ISSUE TITLE
Errors trying to get the test/build process going

### ISSUE THREAD

**Issue by pfw** [unpoly/unpoly#152]
It's been a long time since I've done any amount of Ruby so it's quite possible that I'm messing something up here but after following the README instructions on Development setup I'm getting some Ruby/Rails errors (looking like an infinite recursion) that are beyond my understanding to pick apart.

This is on the hk/layers branch

Any ideas?

```

bundle install --path vendor/bundle

$ GEM_HOME=./vendor/bundle/ruby/2.6.0/ PATH=./vendor/bundle/ruby/2.6.0/bin/:$PATH rails server


/Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/duplicable.rb:85: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Exiting
Traceback (most recent call last):
	8479: from bin/rails:8:in `<main>'
	8478: from bin/rails:8:in `require'
	8477: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	8476: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	8475: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	8474: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	8473: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	8472: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
	 ... 8467 levels...
	   4: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   3: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   2: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   1: from /Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
/Users/pfw/thirdfloor/vendor/unpoly/spec_app/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)

```

**Comment by adam12** [comment]
Can you try the Ruby version in `.ruby-version` for that branch? I think it's 2.3.8.

Also, you shouldn't need to set `GEM_HOME` (tho it's probably not hurting anything). Just `bundle exec rails server` should be sufficient.

**Comment by pfw** [comment]
Success, thanks. I had the correct version of Ruby installed but my original "bundle install" found the wrong one and once I figured out the paths all is ok - at least running now.
