### ISSUE TITLE
Undefined method `menu_lists' in rubydoc documentation

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly#45]
In the sidebar of http://www.rubydoc.info/github/unpoly/unpoly/master there is currently the following stacktrace visible:

```
undefined method `menu_lists' for #<Object:0x007f279691c1b0>
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/fulldoc/html/setup.rb:108:in `menu_lists'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/fulldoc/html/full_list.erb:24:in `_erb_cache_0'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:287:in `erb'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/fulldoc/html/setup.rb:166:in `generate_list_contents'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/fulldoc/html/setup.rb:152:in `generate_class_list'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/commands/list_command.rb:16:in `run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/commands/base.rb:97:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/commands/library_command.rb:74:in `block in call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/commands/library_command.rb:91:in `call_without_fork'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/commands/library_command.rb:74:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/router.rb:159:in `route_list'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/router.rb:116:in `route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/router.rb:56:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/server/rack_adapter.rb:52:in `call'
/home/app/rubydoc.info/app.rb:358:in `block in <class:DocServer>'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `block in compile!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
/home/app/rubydoc.info/app.rb:29:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:205:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `block in call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by denzelem** [comment]
Reloading the page fixed the issue.

**Comment by triskweline** [comment]
That stacktrace is from the app that runs rubydoc.info -- we don't control this.
